modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="pile"
version="Monday - It's Coming (1.14.4)"
displayName="The Pile"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.surrealdave.com"
logoFile="logo.png"
authors="surreal dave"
description='''
join the   p i l e
'''

[[dependencies.pile]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



