// Date: 20/04/2020 3:34:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelMonday extends ModelBase {
	// fields
	ModelRenderer rock;

	public ModelMonday() {
		textureWidth = 256;
		textureHeight = 256;

		rock = new ModelRenderer(this, 0, 0);
		rock.addBox(-32F, -64F, -32F, 64, 64, 64);
		rock.setRotationPoint(0F, 23F, 0F);
		rock.setTextureSize(256, 256);
		rock.mirror = true;
		setRotation(rock, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		rock.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	}

}
