// Date: 1/09/2019 12:41:25 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelCornGolem extends ModelBase {
	// fields
	ModelRenderer larm;
	ModelRenderer body1;
	ModelRenderer rarm;
	ModelRenderer body2;
	ModelRenderer hips;
	ModelRenderer rleg;
	ModelRenderer lleg;
	ModelRenderer neck;
	ModelRenderer head;

	public ModelCornGolem() {
		textureWidth = 64;
		textureHeight = 64;

		larm = new ModelRenderer(this, 0, 0);
		larm.addBox(-6F, -1F, -3F, 6, 22, 6);
		larm.setRotationPoint(-9F, -7.5F, 0F);
		larm.setTextureSize(64, 64);
		larm.mirror = true;
		setRotation(larm, 0F, 0F, 0F);
		body1 = new ModelRenderer(this, 14, 28);
		body1.addBox(-9F, 0F, -3.5F, 18, 9, 7);
		body1.setRotationPoint(0F, -9F, 0F);
		body1.setTextureSize(64, 64);
		body1.mirror = true;
		setRotation(body1, 0F, 0F, 0F);
		rarm = new ModelRenderer(this, 0, 0);
		rarm.addBox(0F, -1F, -3F, 6, 22, 6);
		rarm.setRotationPoint(9F, -7.5F, 0F);
		rarm.setTextureSize(64, 64);
		rarm.mirror = true;
		setRotation(rarm, 0F, 0F, 0F);
		body2 = new ModelRenderer(this, 24, 11);
		body2.addBox(-7F, 0F, -3F, 14, 4, 6);
		body2.setRotationPoint(0F, 0F, 0F);
		body2.setTextureSize(64, 64);
		body2.mirror = true;
		setRotation(body2, 0F, 0F, 0F);
		hips = new ModelRenderer(this, 24, 0);
		hips.addBox(-4.5F, 0F, -2.5F, 9, 6, 5);
		hips.setRotationPoint(0F, 4F, 0F);
		hips.setTextureSize(64, 64);
		hips.mirror = true;
		setRotation(hips, 0F, 0F, 0F);
		rleg = new ModelRenderer(this, 0, 0);
		rleg.addBox(0F, -1F, -3F, 6, 16, 6);
		rleg.setRotationPoint(2F, 9F, 0F);
		rleg.setTextureSize(64, 64);
		rleg.mirror = true;
		setRotation(rleg, 0F, 0F, 0F);
		lleg = new ModelRenderer(this, 0, 0);
		lleg.addBox(-6F, -1F, -3F, 6, 16, 6);
		lleg.setRotationPoint(-2F, 9F, 0F);
		lleg.setTextureSize(64, 64);
		lleg.mirror = true;
		setRotation(lleg, 0F, 0F, 0F);
		neck = new ModelRenderer(this, 40, 44);
		neck.addBox(-3F, -2F, -3F, 6, 2, 6);
		neck.setRotationPoint(0F, -9F, 0F);
		neck.setTextureSize(64, 64);
		neck.mirror = true;
		setRotation(neck, 0F, 0F, 0F);
		head = new ModelRenderer(this, 0, 44);
		head.addBox(-5F, -10F, -5F, 10, 10, 10);
		head.setRotationPoint(0F, -11F, 0F);
		head.setTextureSize(64, 64);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		larm.render(f5);
		body1.render(f5);
		rarm.render(f5);
		body2.render(f5);
		hips.render(f5);
		rleg.render(f5);
		lleg.render(f5);
		neck.render(f5);
		head.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.head.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.head.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.lleg.rotateAngleX = MathHelper.cos(f * 1.0F) * -1.0F * f1;
		this.rleg.rotateAngleX = MathHelper.cos(f * 1.0F) * 1.0F * f1;
		this.rarm.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 2.0F * f1 * 0.5F;
		this.larm.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
	}

}
