// Date: 21/02/2019 3:33:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class Modelohyeahwooyeah extends ModelBase {
	// fields
	ModelRenderer a1;
	ModelRenderer b1;
	ModelRenderer c1;
	ModelRenderer d1;
	ModelRenderer e1;
	ModelRenderer ff;
	ModelRenderer g1;
	ModelRenderer h1;
	ModelRenderer i1;
	ModelRenderer j1;
	ModelRenderer k1;
	ModelRenderer l1;
	ModelRenderer m1;

	public Modelohyeahwooyeah() {
		textureWidth = 32;
		textureHeight = 32;

		a1 = new ModelRenderer(this, 0, 0);
		a1.addBox(-1F, -7F, -0.5F, 2, 7, 1);
		a1.setRotationPoint(7F, 23F, 0F);
		a1.setTextureSize(32, 32);
		a1.mirror = true;
		setRotation(a1, 0F, 0F, 0.0698132F);
		b1 = new ModelRenderer(this, 0, 0);
		b1.addBox(-7F, -1F, -0.5F, 7, 2, 1);
		b1.setRotationPoint(7F, 23F, 0F);
		b1.setTextureSize(32, 32);
		b1.mirror = true;
		setRotation(b1, 0F, 0F, 0F);
		c1 = new ModelRenderer(this, 0, 0);
		c1.addBox(-7F, -1F, -0.5F, 7, 2, 1);
		c1.setRotationPoint(-3F, 20F, 0F);
		c1.setTextureSize(32, 32);
		c1.mirror = true;
		setRotation(c1, 0F, 0F, 0F);
		d1 = new ModelRenderer(this, 0, 0);
		d1.addBox(-10F, -7F, -0.5F, 9, 6, 1);
		d1.setRotationPoint(9.666667F, 11F, 0F);
		d1.setTextureSize(32, 32);
		d1.mirror = true;
		setRotation(d1, 0F, 0F, 0F);
		e1 = new ModelRenderer(this, 0, 0);
		e1.addBox(-2F, -7F, -0.5F, 3, 7, 1);
		e1.setRotationPoint(-3F, 20F, 0F);
		e1.setTextureSize(32, 32);
		e1.mirror = true;
		setRotation(e1, 0F, 0F, 0.0698132F);
		ff = new ModelRenderer(this, 0, 0);
		ff.addBox(-2F, -7F, -0.5F, 3, 7, 1);
		ff.setRotationPoint(-3F, 14F, 0F);
		ff.setTextureSize(32, 32);
		ff.mirror = true;
		setRotation(ff, 0F, 0F, 0.7330383F);
		g1 = new ModelRenderer(this, 0, 0);
		g1.addBox(-2F, -7F, -0.5F, 3, 7, 1);
		g1.setRotationPoint(8F, 17F, 0F);
		g1.setTextureSize(32, 32);
		g1.mirror = true;
		setRotation(g1, 0F, 0F, 0.3665191F);
		h1 = new ModelRenderer(this, 0, 0);
		h1.addBox(-7F, -13F, -0.5F, 9, 7, 1);
		h1.setRotationPoint(1.666667F, 3F, 0F);
		h1.setTextureSize(32, 32);
		h1.mirror = true;
		setRotation(h1, 0F, 0F, 0F);
		i1 = new ModelRenderer(this, 0, 0);
		i1.addBox(-4F, 0F, -0.5F, 15, 2, 1);
		i1.setRotationPoint(-12F, 0F, 0F);
		i1.setTextureSize(32, 32);
		i1.mirror = true;
		setRotation(i1, 0F, 0F, 0F);
		j1 = new ModelRenderer(this, 0, 0);
		j1.addBox(0F, 0F, -0.5F, 12, 2, 1);
		j1.setRotationPoint(-12F, 4F, 0F);
		j1.setTextureSize(32, 32);
		j1.mirror = true;
		setRotation(j1, 0F, 0F, 0F);
		k1 = new ModelRenderer(this, 0, 0);
		k1.addBox(-2F, -6F, -0.5F, 3, 6, 1);
		k1.setRotationPoint(10.66667F, 11F, 0F);
		k1.setTextureSize(32, 32);
		k1.mirror = true;
		setRotation(k1, 0F, 0F, 0F);
		l1 = new ModelRenderer(this, 0, 0);
		l1.addBox(-3F, -9F, -0.5F, 7, 7, 1);
		l1.setRotationPoint(2.666667F, 7F, 0F);
		l1.setTextureSize(32, 32);
		l1.mirror = true;
		setRotation(l1, 0F, 0F, -0.1396263F);
		m1 = new ModelRenderer(this, 0, 0);
		m1.addBox(-3F, -7F, -0.5F, 5, 3, 1);
		m1.setRotationPoint(1.666667F, 3F, 0F);
		m1.setTextureSize(32, 32);
		m1.mirror = true;
		setRotation(m1, 0F, 0F, -0.0698132F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		a1.render(f5);
		b1.render(f5);
		c1.render(f5);
		d1.render(f5);
		e1.render(f5);
		ff.render(f5);
		g1.render(f5);
		h1.render(f5);
		i1.render(f5);
		j1.render(f5);
		k1.render(f5);
		l1.render(f5);
		m1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	}

}
