// Date: 21/12/2019 4:14:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelBaseballCap extends ModelBase {
	// fields
	ModelRenderer hat2;
	ModelRenderer hat1;

	public ModelBaseballCap() {
		textureWidth = 64;
		textureHeight = 32;

		hat2 = new ModelRenderer(this, 3, 6);
		hat2.addBox(-4F, -5.1F, -9F, 8, 1, 5);
		hat2.setRotationPoint(0F, 0F, 0F);
		hat2.setTextureSize(64, 32);
		hat2.mirror = true;
		setRotation(hat2, 0F, 0F, 0F);
		hat1 = new ModelRenderer(this, 0, 0);
		hat1.addBox(-4F, -8.1F, -4F, 8, 4, 8);
		hat1.setRotationPoint(0F, 0F, 0F);
		hat1.setTextureSize(64, 32);
		hat1.mirror = true;
		setRotation(hat1, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		hat2.render(f5);
		hat1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
