// Date: 2/03/2019 4:52:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelWheelchair extends ModelBase {
	// fields
	ModelRenderer w2;
	ModelRenderer w1;
	ModelRenderer back;
	ModelRenderer seat;
	ModelRenderer h2;
	ModelRenderer h1;
	ModelRenderer rl2;
	ModelRenderer rl1;
	ModelRenderer ll1;
	ModelRenderer ll2;
	ModelRenderer la;
	ModelRenderer ra;

	public ModelWheelchair() {
		textureWidth = 64;
		textureHeight = 32;

		w2 = new ModelRenderer(this, 0, 2);
		w2.addBox(0F, -5F, -5F, 0, 10, 10);
		w2.setRotationPoint(-5F, 19F, 0F);
		w2.setTextureSize(64, 32);
		w2.mirror = true;
		setRotation(w2, 0F, 0F, 0F);
		w1 = new ModelRenderer(this, 0, 2);
		w1.addBox(0F, -5F, -5F, 0, 10, 10);
		w1.setRotationPoint(5F, 19F, 0F);
		w1.setTextureSize(64, 32);
		w1.mirror = true;
		setRotation(w1, 0F, 0F, 0F);
		back = new ModelRenderer(this, 0, 0);
		back.addBox(-5F, 3F, 0F, 10, 2, 10);
		back.setRotationPoint(0F, 17F, 0F);
		back.setTextureSize(64, 32);
		back.mirror = true;
		setRotation(back, 1.396263F, 0F, 0F);
		seat = new ModelRenderer(this, 0, 0);
		seat.addBox(-5F, -1F, -5F, 10, 2, 10);
		seat.setRotationPoint(0F, 17F, 0F);
		seat.setTextureSize(64, 32);
		seat.mirror = true;
		setRotation(seat, 0F, 0F, 0F);
		h2 = new ModelRenderer(this, 30, 0);
		h2.addBox(-4F, 0F, 0F, 1, 1, 4);
		h2.setRotationPoint(0F, 7F, 5F);
		h2.setTextureSize(64, 32);
		h2.mirror = true;
		setRotation(h2, 0F, 0F, 0F);
		h1 = new ModelRenderer(this, 30, 0);
		h1.addBox(3F, 0F, 0F, 1, 1, 4);
		h1.setRotationPoint(0F, 7F, 5F);
		h1.setTextureSize(64, 32);
		h1.mirror = true;
		setRotation(h1, 0F, 0F, 0F);
		rl2 = new ModelRenderer(this, 0, 5);
		rl2.addBox(-1F, 3F, -2F, 2, 1, 2);
		rl2.setRotationPoint(-3F, 18F, -5F);
		rl2.setTextureSize(64, 32);
		rl2.mirror = true;
		setRotation(rl2, -0.1745329F, 0F, 0F);
		rl1 = new ModelRenderer(this, 0, 0);
		rl1.addBox(-1F, 0F, 0F, 2, 4, 1);
		rl1.setRotationPoint(-3F, 18F, -5F);
		rl1.setTextureSize(64, 32);
		rl1.mirror = true;
		setRotation(rl1, -0.1745329F, 0F, 0F);
		ll1 = new ModelRenderer(this, 0, 0);
		ll1.addBox(-1F, 0F, 0F, 2, 4, 1);
		ll1.setRotationPoint(3F, 18F, -5F);
		ll1.setTextureSize(64, 32);
		ll1.mirror = true;
		setRotation(ll1, -0.1745329F, 0F, 0F);
		ll2 = new ModelRenderer(this, 0, 5);
		ll2.addBox(-1F, 3F, -2F, 2, 1, 2);
		ll2.setRotationPoint(3F, 18F, -5F);
		ll2.setTextureSize(64, 32);
		ll2.mirror = true;
		setRotation(ll2, -0.1745329F, 0F, 0F);
		la = new ModelRenderer(this, 40, 0);
		la.addBox(-1F, 0F, -10F, 2, 1, 10);
		la.setRotationPoint(5F, 13F, 4F);
		la.setTextureSize(64, 32);
		la.mirror = true;
		setRotation(la, 0F, 0F, 0F);
		ra = new ModelRenderer(this, 40, 0);
		ra.addBox(-1F, 0F, -10F, 2, 1, 10);
		ra.setRotationPoint(-5F, 13F, 4F);
		ra.setTextureSize(64, 32);
		ra.mirror = true;
		setRotation(ra, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		w2.render(f5);
		w1.render(f5);
		back.render(f5);
		seat.render(f5);
		h2.render(f5);
		h1.render(f5);
		rl2.render(f5);
		rl1.render(f5);
		ll1.render(f5);
		ll2.render(f5);
		la.render(f5);
		ra.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
