// Date: 21/02/2019 2:11:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelMoyai extends ModelBase {
	// fields
	ModelRenderer base;
	ModelRenderer n1;
	ModelRenderer n2;
	ModelRenderer b2;
	ModelRenderer b1;
	ModelRenderer m2;
	ModelRenderer m1;
	ModelRenderer e;

	public ModelMoyai() {
		textureWidth = 64;
		textureHeight = 128;

		base = new ModelRenderer(this, 0, 0);
		base.addBox(-8F, 0F, -8F, 16, 28, 16);
		base.setRotationPoint(0F, -4F, 0F);
		base.setTextureSize(64, 128);
		base.mirror = true;
		setRotation(base, 0F, 0F, 0F);
		n1 = new ModelRenderer(this, 0, 56);
		n1.addBox(-3F, -9F, -1F, 6, 9, 1);
		n1.setRotationPoint(0F, 11F, -8F);
		n1.setTextureSize(64, 128);
		n1.mirror = true;
		setRotation(n1, 0F, 0F, 0F);
		n2 = new ModelRenderer(this, 0, 72);
		n2.addBox(-5F, 0F, -1F, 10, 6, 2);
		n2.setRotationPoint(0F, 11F, -9F);
		n2.setTextureSize(64, 128);
		n2.mirror = true;
		setRotation(n2, 0F, 0F, 0F);
		b2 = new ModelRenderer(this, 0, 50);
		b2.addBox(-8F, -1.5F, -9F, 16, 5, 1);
		b2.setRotationPoint(0F, -2F, 0F);
		b2.setTextureSize(64, 128);
		b2.mirror = true;
		setRotation(b2, 0F, 0F, 0F);
		b1 = new ModelRenderer(this, 0, 44);
		b1.addBox(-8F, 0F, -10F, 16, 4, 2);
		b1.setRotationPoint(0F, -3F, 0F);
		b1.setTextureSize(64, 128);
		b1.mirror = true;
		setRotation(b1, 0F, 0F, 0F);
		m2 = new ModelRenderer(this, 42, 44);
		m2.addBox(-5F, 0F, 0.5F, 10, 2, 1);
		m2.setRotationPoint(0F, 21F, -9F);
		m2.setTextureSize(64, 128);
		m2.mirror = true;
		setRotation(m2, 0F, 0F, 0F);
		m1 = new ModelRenderer(this, 42, 44);
		m1.addBox(-5F, 0F, 0F, 10, 2, 1);
		m1.setRotationPoint(0F, 19F, -9F);
		m1.setTextureSize(64, 128);
		m1.mirror = true;
		setRotation(m1, 0F, 0F, 0F);
		e = new ModelRenderer(this, 14, 56);
		e.addBox(-9F, 3F, 0F, 18, 9, 7);
		e.setRotationPoint(0F, 0F, 0F);
		e.setTextureSize(64, 128);
		e.mirror = true;
		setRotation(e, -0.3926991F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		base.render(f5);
		n1.render(f5);
		n2.render(f5);
		b2.render(f5);
		b1.render(f5);
		m2.render(f5);
		m1.render(f5);
		e.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
