// Date: 27/12/2018 6:45:31 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelMolbo extends ModelBase {
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer eye1;
	ModelRenderer eye2;
	ModelRenderer ll2;
	ModelRenderer ll1;
	ModelRenderer rl1;
	ModelRenderer ll3;
	ModelRenderer rl2;
	ModelRenderer rl3;

	public ModelMolbo() {
		textureWidth = 64;
		textureHeight = 32;

		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, 0F, -1F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		body = new ModelRenderer(this, 32, 0);
		body.addBox(-3F, 0F, -2F, 6, 9, 4);
		body.setRotationPoint(0F, 0F, 0F);
		body.setTextureSize(64, 32);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		eye1 = new ModelRenderer(this, 24, 0);
		eye1.addBox(-3.5F, -6F, -4.5F, 3, 3, 1);
		eye1.setRotationPoint(0F, 0F, -1F);
		eye1.setTextureSize(64, 32);
		eye1.mirror = true;
		setRotation(eye1, 0F, 0F, 0F);
		eye2 = new ModelRenderer(this, 24, 0);
		eye2.addBox(0.5F, -6F, -4.5F, 3, 3, 1);
		eye2.setRotationPoint(0F, 0F, -1F);
		eye2.setTextureSize(64, 32);
		eye2.mirror = true;
		setRotation(eye2, 0F, 0F, 0F);
		ll2 = new ModelRenderer(this, 0, 16);
		ll2.addBox(2.5F, 6F, -2F, 4, 8, 4);
		ll2.setRotationPoint(0F, 9F, 0F);
		ll2.setTextureSize(64, 32);
		ll2.mirror = true;
		setRotation(ll2, 0F, 0F, 0F);
		ll1 = new ModelRenderer(this, 0, 16);
		ll1.addBox(0F, 0F, -2F, 4, 8, 4);
		ll1.setRotationPoint(0F, 9F, 0F);
		ll1.setTextureSize(64, 32);
		ll1.mirror = true;
		setRotation(ll1, 0F, 0F, -0.3490659F);
		rl1 = new ModelRenderer(this, 0, 16);
		rl1.addBox(-4F, 0F, -2F, 4, 8, 4);
		rl1.setRotationPoint(0F, 9F, 0F);
		rl1.setTextureSize(64, 32);
		rl1.mirror = true;
		setRotation(rl1, 0F, 0F, 0.3490659F);
		ll3 = new ModelRenderer(this, 16, 16);
		ll3.addBox(2.466667F, 13F, -4F, 4, 2, 6);
		ll3.setRotationPoint(0F, 9F, 0F);
		ll3.setTextureSize(64, 32);
		ll3.mirror = true;
		setRotation(ll3, 0F, 0F, 0F);
		rl2 = new ModelRenderer(this, 0, 16);
		rl2.addBox(-6.533333F, 6F, -2F, 4, 8, 4);
		rl2.setRotationPoint(0F, 9F, 0F);
		rl2.setTextureSize(64, 32);
		rl2.mirror = true;
		setRotation(rl2, 0F, 0F, 0F);
		rl3 = new ModelRenderer(this, 16, 16);
		rl3.addBox(-6.533333F, 13F, -4F, 4, 2, 6);
		rl3.setRotationPoint(0F, 9F, 0F);
		rl3.setTextureSize(64, 32);
		rl3.mirror = true;
		setRotation(rl3, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		head.render(f5);
		body.render(f5);
		eye1.render(f5);
		eye2.render(f5);
		ll2.render(f5);
		ll1.render(f5);
		rl1.render(f5);
		ll3.render(f5);
		rl2.render(f5);
		rl3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.ll3.rotateAngleX = MathHelper.cos(f * 1.0F) * -1.0F * f1;
		this.rl3.rotateAngleX = MathHelper.cos(f * 1.0F) * 1.0F * f1;
	}

}
