// Date: 23/02/2019 3:34:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelGarlicKing extends ModelBase {
	// fields
	ModelRenderer ll1;
	ModelRenderer ll2;
	ModelRenderer lf;
	ModelRenderer lt1;
	ModelRenderer lt2;
	ModelRenderer rf;
	ModelRenderer rl2;
	ModelRenderer rl1;
	ModelRenderer rt1;
	ModelRenderer rt2;
	ModelRenderer s2;
	ModelRenderer crown;
	ModelRenderer s1;
	ModelRenderer body;

	public ModelGarlicKing() {
		textureWidth = 128;
		textureHeight = 128;

		ll1 = new ModelRenderer(this, 0, 0);
		ll1.addBox(2F, 0F, -5F, 10, 12, 10);
		ll1.setRotationPoint(0F, 0F, 0F);
		ll1.setTextureSize(128, 128);
		ll1.mirror = true;
		setRotation(ll1, -0.0349066F, 0F, -0.0523599F);
		ll2 = new ModelRenderer(this, 0, 0);
		ll2.addBox(2F, 11.06667F, -5.666667F, 10, 12, 10);
		ll2.setRotationPoint(0F, 0F, 0F);
		ll2.setTextureSize(128, 128);
		ll2.mirror = true;
		setRotation(ll2, 0.0174533F, 0F, -0.0523599F);
		lf = new ModelRenderer(this, 40, 0);
		lf.addBox(2F, 20.06667F, -6.666667F, 10, 4, 12);
		lf.setRotationPoint(0F, 0F, 0F);
		lf.setTextureSize(128, 128);
		lf.mirror = true;
		setRotation(lf, 0.0174533F, 0F, -0.0523599F);
		lt1 = new ModelRenderer(this, 0, 22);
		lt1.addBox(7F, 22.06667F, -14.66667F, 5, 2, 8);
		lt1.setRotationPoint(0F, 0F, 0F);
		lt1.setTextureSize(128, 128);
		lt1.mirror = true;
		setRotation(lt1, 0.0523599F, -0.0872665F, -0.0523599F);
		lt2 = new ModelRenderer(this, 0, 22);
		lt2.addBox(2F, 22.06667F, -13.66667F, 5, 2, 8);
		lt2.setRotationPoint(0F, 0F, 0F);
		lt2.setTextureSize(128, 128);
		lt2.mirror = true;
		setRotation(lt2, 0.0349066F, 0.0872665F, -0.0523599F);
		rf = new ModelRenderer(this, 40, 0);
		rf.addBox(-12F, 20.06667F, -6.666667F, 10, 4, 12);
		rf.setRotationPoint(0F, 0F, 0F);
		rf.setTextureSize(128, 128);
		rf.mirror = true;
		setRotation(rf, 0.0174533F, 0F, 0.0523599F);
		rl2 = new ModelRenderer(this, 0, 0);
		rl2.addBox(-12F, 11.06667F, -5.666667F, 10, 12, 10);
		rl2.setRotationPoint(0F, 0F, 0F);
		rl2.setTextureSize(128, 128);
		rl2.mirror = true;
		setRotation(rl2, 0.0174533F, 0F, 0.0523599F);
		rl1 = new ModelRenderer(this, 0, 0);
		rl1.addBox(-12F, 0F, -5F, 10, 12, 10);
		rl1.setRotationPoint(0F, 0F, 0F);
		rl1.setTextureSize(128, 128);
		rl1.mirror = true;
		setRotation(rl1, -0.0349066F, 0F, 0.0523599F);
		rt1 = new ModelRenderer(this, 0, 22);
		rt1.addBox(-12F, 22.06667F, -14.66667F, 5, 2, 8);
		rt1.setRotationPoint(0F, 0F, 0F);
		rt1.setTextureSize(128, 128);
		rt1.mirror = true;
		setRotation(rt1, 0.0523599F, 0.0872665F, 0.0523599F);
		rt2 = new ModelRenderer(this, 0, 22);
		rt2.addBox(-7F, 22.06667F, -13.66667F, 5, 2, 8);
		rt2.setRotationPoint(0F, 0F, 0F);
		rt2.setTextureSize(128, 128);
		rt2.mirror = true;
		setRotation(rt2, 0.0349066F, -0.0872665F, 0.0523599F);
		s2 = new ModelRenderer(this, 54, 22);
		s2.addBox(0F, -34F, 8.2F, 4, 8, 4);
		s2.setRotationPoint(0F, 0F, 0F);
		s2.setTextureSize(128, 128);
		s2.mirror = true;
		setRotation(s2, 0.1570796F, 0.1396263F, 0.1047198F);
		crown = new ModelRenderer(this, 0, 88);
		crown.addBox(-15F, -34F, -15F, 30, 10, 30);
		crown.setRotationPoint(0F, 0F, 0F);
		crown.setTextureSize(128, 128);
		crown.mirror = true;
		setRotation(crown, 0F, 0F, 0F);
		s1 = new ModelRenderer(this, 70, 17);
		s1.addBox(-4F, -27F, -3F, 15, 3, 14);
		s1.setRotationPoint(0F, 0F, 0F);
		s1.setTextureSize(128, 128);
		s1.mirror = true;
		setRotation(s1, 0F, 0F, 0F);
		body = new ModelRenderer(this, 0, 34);
		body.addBox(-15F, -24F, -15F, 30, 24, 30);
		body.setRotationPoint(0F, 0F, 0F);
		body.setTextureSize(128, 128);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		ll1.render(f5);
		ll2.render(f5);
		lf.render(f5);
		lt1.render(f5);
		lt2.render(f5);
		rf.render(f5);
		rl2.render(f5);
		rl1.render(f5);
		rt1.render(f5);
		rt2.render(f5);
		s2.render(f5);
		crown.render(f5);
		s1.render(f5);
		body.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.ll1.rotateAngleX = MathHelper.cos(f * 1.0F) * -1.0F * f1;
		this.rl1.rotateAngleX = MathHelper.cos(f * 1.0F) * 1.0F * f1;
	}

}
