// Date: 2/03/2019 5:45:51 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelIsopod extends ModelBase {
	// fields
	ModelRenderer b1;
	ModelRenderer head;
	ModelRenderer b3;
	ModelRenderer b2;
	ModelRenderer fin2;
	ModelRenderer fin1;
	ModelRenderer legs;
	ModelRenderer tail;

	public ModelIsopod() {
		textureWidth = 64;
		textureHeight = 32;

		b1 = new ModelRenderer(this, 0, 22);
		b1.addBox(-3F, -3.5F, -3F, 6, 4, 6);
		b1.setRotationPoint(0F, 23F, -3F);
		b1.setTextureSize(64, 32);
		b1.mirror = true;
		setRotation(b1, -0.0918105F, 0F, 0F);
		head = new ModelRenderer(this, 16, 12);
		head.addBox(-2F, -2F, -2F, 4, 3, 2);
		head.setRotationPoint(0F, 22F, -5.6F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		b3 = new ModelRenderer(this, 42, 27);
		b3.addBox(-2.5F, -2F, 3F, 5, 3, 2);
		b3.setRotationPoint(0F, 23F, -0.2F);
		b3.setTextureSize(64, 32);
		b3.mirror = true;
		setRotation(b3, 0F, 0F, 0F);
		b2 = new ModelRenderer(this, 24, 25);
		b2.addBox(-3F, -2F, 0F, 6, 4, 3);
		b2.setRotationPoint(0F, 22F, -0.2F);
		b2.setTextureSize(64, 32);
		b2.mirror = true;
		setRotation(b2, 0F, 0F, 0F);
		fin2 = new ModelRenderer(this, 0, 12);
		fin2.addBox(-4.5F, 0F, -5.5F, 3, 0, 10);
		fin2.setRotationPoint(0F, 23F, -1F);
		fin2.setTextureSize(64, 32);
		fin2.mirror = true;
		setRotation(fin2, -0.0698132F, 0F, -0.1745329F);
		fin1 = new ModelRenderer(this, -6, 12);
		fin1.addBox(1.5F, 0F, -5.5F, 3, 0, 10);
		fin1.setRotationPoint(0F, 23F, -1F);
		fin1.setTextureSize(64, 32);
		fin1.mirror = true;
		setRotation(fin1, -0.0698132F, 0F, 0.1745329F);
		legs = new ModelRenderer(this, 0, 4);
		legs.addBox(-2F, 0F, -5.5F, 4, 1, 7);
		legs.setRotationPoint(0F, 23F, -1F);
		legs.setTextureSize(64, 32);
		legs.mirror = true;
		setRotation(legs, 0F, 0F, 0F);
		tail = new ModelRenderer(this, 12, 18);
		tail.addBox(-3.5F, 0F, 0F, 7, 0, 4);
		tail.setRotationPoint(0F, 23.5F, 4F);
		tail.setTextureSize(64, 32);
		tail.mirror = true;
		setRotation(tail, -0.0872665F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		b1.render(f5);
		head.render(f5);
		b3.render(f5);
		b2.render(f5);
		fin2.render(f5);
		fin1.render(f5);
		legs.render(f5);
		tail.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.head.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.head.rotateAngleX = f4 / (180F / (float) Math.PI);
	}

}
