// Date: 14/05/2019 3:47:20 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelWormWithEyes extends ModelBase {
	// fields
	ModelRenderer b8;
	ModelRenderer b2;
	ModelRenderer bb3;
	ModelRenderer b4;
	ModelRenderer b5;
	ModelRenderer b6;
	ModelRenderer b7;
	ModelRenderer e2;
	ModelRenderer b1;
	ModelRenderer m;
	ModelRenderer e1;

	public ModelWormWithEyes() {
		textureWidth = 64;
		textureHeight = 32;

		b8 = new ModelRenderer(this, 0, 0);
		b8.addBox(-1F, -1F, -2F, 2, 2, 2);
		b8.setRotationPoint(1F, 23.5F, 8F);
		b8.setTextureSize(64, 32);
		b8.mirror = true;
		setRotation(b8, 0F, 0F, 0F);
		b2 = new ModelRenderer(this, 0, 0);
		b2.addBox(-1F, -1F, -2F, 2, 2, 2);
		b2.setRotationPoint(-1F, 23F, -4F);
		b2.setTextureSize(64, 32);
		b2.mirror = true;
		setRotation(b2, 0F, 0F, 0F);
		bb3 = new ModelRenderer(this, 0, 0);
		bb3.addBox(-1F, -1F, -2F, 2, 2, 2);
		bb3.setRotationPoint(-2F, 23.5F, -2F);
		bb3.setTextureSize(64, 32);
		bb3.mirror = true;
		setRotation(bb3, 0F, 0F, 0F);
		b4 = new ModelRenderer(this, 0, 0);
		b4.addBox(-1F, -1F, -2F, 2, 2, 2);
		b4.setRotationPoint(-1F, 23.5F, 0F);
		b4.setTextureSize(64, 32);
		b4.mirror = true;
		setRotation(b4, 0F, 0F, 0F);
		b5 = new ModelRenderer(this, 0, 0);
		b5.addBox(-1F, -1F, -2F, 2, 2, 2);
		b5.setRotationPoint(0F, 23.5F, 2F);
		b5.setTextureSize(64, 32);
		b5.mirror = true;
		setRotation(b5, 0F, 0F, 0F);
		b6 = new ModelRenderer(this, 0, 0);
		b6.addBox(-1F, -1F, -2F, 2, 2, 2);
		b6.setRotationPoint(1F, 23.5F, 4F);
		b6.setTextureSize(64, 32);
		b6.mirror = true;
		setRotation(b6, 0F, 0F, 0F);
		b7 = new ModelRenderer(this, 0, 0);
		b7.addBox(-1F, -1F, -2F, 2, 2, 2);
		b7.setRotationPoint(2F, 23.5F, 6F);
		b7.setTextureSize(64, 32);
		b7.mirror = true;
		setRotation(b7, 0F, 0F, 0F);
		e2 = new ModelRenderer(this, 0, 4);
		e2.addBox(0.5F, -1F, -2.5F, 1, 1, 1);
		e2.setRotationPoint(0F, 22.5F, -6F);
		e2.setTextureSize(64, 32);
		e2.mirror = true;
		setRotation(e2, 0F, 0F, 0F);
		b1 = new ModelRenderer(this, 0, 0);
		b1.addBox(-1F, -1F, -2F, 2, 2, 2);
		b1.setRotationPoint(0F, 22.5F, -6F);
		b1.setTextureSize(64, 32);
		b1.mirror = true;
		setRotation(b1, 0F, 0F, 0F);
		m = new ModelRenderer(this, 0, 6);
		m.addBox(-0.5F, 0F, -2.25F, 1, 1, 1);
		m.setRotationPoint(0F, 22.5F, -6F);
		m.setTextureSize(64, 32);
		m.mirror = true;
		setRotation(m, 0F, 0F, 0F);
		e1 = new ModelRenderer(this, 0, 4);
		e1.addBox(-1.5F, -1F, -2.5F, 1, 1, 1);
		e1.setRotationPoint(0F, 22.5F, -6F);
		e1.setTextureSize(64, 32);
		e1.mirror = true;
		setRotation(e1, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		b8.render(f5);
		b2.render(f5);
		bb3.render(f5);
		b4.render(f5);
		b5.render(f5);
		b6.render(f5);
		b7.render(f5);
		e2.render(f5);
		b1.render(f5);
		m.render(f5);
		e1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.e1.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.e1.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.e2.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.e2.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.m.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.m.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.b1.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.b1.rotateAngleX = f4 / (180F / (float) Math.PI);
	}

}
